# -*- mode: ruby -*-
# vi: set ft=ruby :

BASE_BOX_NAME = 'ubuntu/trusty64'

Vagrant.configure('2') do |config|

  config.vm.define :puppet_desktop do |puppet_desktop|
    puppet_desktop.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '2048']
    end
    puppet_desktop.vm.box = BASE_BOX_NAME
    puppet_desktop.vm.hostname = 'pup'
    puppet_desktop.vm.synced_folder "../", "/home/vagrant/puppet-desktop", create: true
    puppet_desktop.vm.provision "shell", path: "provision.sh", privileged: false
  end

end
